const initialData = {
  values: {
    'value-1': {id: 'value-1', content: 'Flexibility'},
    'value-2': {id: 'value-2', content: 'Adaptability'},
    'value-3': {id: 'value-3', content: 'Stability'},
    'value-4': {id: 'value-4', content: 'Predictability'},
    'value-5': {id: 'value-5', content: 'Being innovative'},
    'value-6': {id: 'value-6', content: 'Being quick to take advantage of opportunities'},
    'value-7': {id: 'value-7', content: 'A willingness to experiment'},
    'value-8': {id: 'value-8', content: 'Risk taking'},
    'value-9': {id: 'value-9', content: 'Autonomy'},
    'value-10': {id: 'value-10', content: 'Being rule oriented'},
    'value-11': {id: 'value-11', content: 'Being analytical'},
    'value-12': {id: 'value-12', content: 'Paying attention to detail'},
    'value-13': {id: 'value-13', content: 'Being precise'},
    'value-14': {id: 'value-14', content: 'Being team oriented'},
    'value-15': {id: 'value-15', content: 'Sharing information freely'},
    'value-16': {id: 'value-16', content: 'Emphasizing a single culture throughout the organization'},
    'value-17': {id: 'value-17', content: 'Being people oriented'},
    'value-18': {id: 'value-18', content: 'Fairness'},
    'value-19': {id: 'value-19', content: 'Respect for the individua\'s right'},
    'value-20': {id: 'value-20', content: 'Tolerance'},
    'value-21': {id: 'value-21', content: 'Informality'},
    'value-22': {id: 'value-22', content: 'Being easy going'},
    'value-23': {id: 'value-23', content: 'Being calm'},
    'value-24': {id: 'value-24', content: 'Being supportive'},
    'value-25': {id: 'value-25', content: 'Being aggressive'},
    'value-26': {id: 'value-26', content: 'Decisiveness'},
    'value-27': {id: 'value-27', content: 'Action orientation'},
    'value-28': {id: 'value-28', content: 'Taking initiative'},
    'value-29': {id: 'value-29', content: 'Being reflective'},
    'value-30': {id: 'value-30', content: 'Achievement orientation'},
    'value-31': {id: 'value-31', content: 'Being demanding'},
    'value-32': {id: 'value-32', content: 'Taking individual responsibility'},
    'value-33': {id: 'value-33', content: 'Having high expectations for performance'},
    'value-34': {id: 'value-34', content: 'Opportunities for professional growth'},
    'value-35': {id: 'value-35', content: 'High pay for good performance'},
    'value-36': {id: 'value-36', content: 'Security of employment'},
    'value-37': {id: 'value-37', content: 'Offers praise for good performance'},
    'value-38': {id: 'value-38', content: 'Confronting conflict directly'},
    'value-39': {id: 'value-39', content: 'Developing friends at work'},
    'value-40': {id: 'value-40', content: 'Fitting in'},
    'value-41': {id: 'value-41', content: 'Working in collaboration with others'},
    'value-42': {id: 'value-42', content: 'Enthusiasm for the job'},
    'value-43': {id: 'value-43', content: 'Working long hours'},
    'value-44': {id: 'value-44', content: 'Not being constrained by many rules'},
    'value-45': {id: 'value-45', content: 'An emphasis on quality'},
    'value-46': {id: 'value-46', content: 'Being distinctive-different from others'},
    'value-47': {id: 'value-47', content: 'Having a good reputation'},
    'value-48': {id: 'value-48', content: 'Being socially responsible'},
    'value-49': {id: 'value-49', content: 'Being result oriented'},
    'value-50': {id: 'value-50', content: 'Having a clear guiding philosophy'},
    'value-51': {id: 'value-51', content: 'Being competitive'},
    'value-52': {id: 'value-52', content: 'Being highly organized'},
    'value-53': {id: 'value-53', content: 'Being careful'},
    'value-54': {id: 'value-54', content: 'Low level of conflict'},
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Work-related values',
      valueIds: ['value-1', 'value-2', 'value-3', 'value-4', 'value-5', 'value-6',
       'value-7', 'value-8', 'value-9', 'value-10', 'value-11', 'value-12',
       'value-13', 'value-14', 'value-15', 'value-16', 'value-17', 'value-18',
       'value-19', 'value-20', 'value-21', 'value-22', 'value-23', 'value-24',
       'value-25', 'value-26', 'value-27', 'value-28', 'value-29', 'value-30',
       'value-31', 'value-32', 'value-33', 'value-34', 'value-35', 'value-36',
       'value-37', 'value-38', 'value-39', 'value-40', 'value-41', 'value-42',
       'value-43', 'value-44', 'value-45', 'value-46', 'value-47', 'value-48',
       'value-49', 'value-50', 'value-51', 'value-52', 'value-53'],
       limit: 54,
     },
     'column-2': {
       id: 'column-2',
       title: 'Most Important, Rank #1',
       valueIds: [],
       limit: 2,
     },
     'column-3': {
       id: 'column-3',
       title: 'Importance Rank #2',
       valueIds: [],
       limit: 4,
     },
     'column-4': {
       id: 'column-4',
       title: 'Importance Rank #3',
       valueIds: [],
       limit: 6,
     },
     'column-5': {
       id: 'column-5',
       title: 'Importance Rank #4',
       valueIds: [],
       limit: 9,
     },
     'column-6': {
       id: 'column-6',
       title: 'Importance Rank #5',
       valueIds: [],
       limit: 12,
     },
     'column-7': {
       id: 'column-7',
       title: 'Importance Rank #6',
       valueIds: [],
       limit: 9,
     },
     'column-8': {
       id: 'column-8',
       title: 'Importance Rank #7',
       valueIds: [],
       limit: 6,
     },
     'column-9': {
       id: 'column-9',
       title: 'Importance Rank #8',
       valueIds: [],
       limit: 4,
     },
     'column-10': {
       id: 'column-10',
       title: 'Importance Rank #9',
       valueIds: [],
       limit: 2,
     },
   },
   // facilitate reordering of the columns
   columnOrder: ['column-1', 'column-2', 'column-3', 'column-4', 'column-5',
                 'column-6', 'column-7', 'column-8', 'column-9', 'column-10',],
};

export default initialData;
